"use client";
import Image from "next/image";
import { useState } from "react";

export default function CatalogoExpectativa() {
  const [wishlistMsg, setWishlistMsg] = useState<string | null>(null);

    const handleWishlist = (productName: string) => {
        setWishlistMsg(`Has añadido ${productName} a tu Lista de Deseos. Te avisaremos cuando esté listo.`);
            setTimeout(() => setWishlistMsg(null), 3000);
              };

                // Datos extraídos del Plan de Trabajo
                  const productosFuturos = [
                      {
                            id: "velon",
                                  name: "Velón de Poder — El Heraldo",
                                        desc: "No es el ritual en sí — es la proclamación que lo autoriza. Enciéndelo para declarar tu intención al inicio de cualquier operación: activa tus Oleums, despierta a tus Ídolos y anuncia tu voluntad.",
                                              image: "/placeholder-velon.png" // Tú subirás esta imagen después
                                                  },
                                                      {
                                                            id: "polvo",
                                                                  name: "Polvo Mágico — El Alquimista de Corte",
                                                                        desc: "No es el ritual, es el catalizador que transforma un objeto común en un objeto consagrado. Úsalo para vestir tus velas, consagrar tus Ídolos o marcar el espacio antes de una operación.",
                                                                              image: "/placeholder-polvo.png"
                                                                                  },
                                                                                      {
                                                                                            id: "poppet",
                                                                                                  name: "Poppet — Hamelin's Children",
                                                                                                        desc: "Vehículo de magia simpática que permite dirigir la energía de un ritual hacia un tercero o hacia uno mismo, sin necesidad de contacto directo. Alternativa ideal para quienes prefieren no aplicar Oleums en su piel.",
                                                                                                              image: "/placeholder-poppet.png"
                                                                                                                  },
                                                                                                                      {
                                                                                                                            id: "idolos",
                                                                                                                                  name: "Ídolos de Madera Consagrados",
                                                                                                                                        desc: "No basta con nombrar a un espíritu: hay que darle un cuerpo. Cada Ídolo (Claunech, Frimost, Clisthert, Guland, Frutimiere, Surgat) se solicita, se talla y se bautiza de forma individual para quien lo adquiere.",
                                                                                                                                              image: "/placeholder-idolos.png"
                                                                                                                                                  }
                                                                                                                                                    ];

                                                                                                                                                      return (
                                                                                                                                                          <section className="w-full max-w-6xl mx-auto px-6 py-16 text-gray-200 z-20 relative">
                                                                                                                                                                
                                                                                                                                                                      {/* TÍTULO DE SECCIÓN */}
                                                                                                                                                                            <div className="w-full text-center mb-10">
                                                                                                                                                                                    <h3 className="text-3xl md:text-4xl font-cinzel text-purple-300 mb-4 drop-shadow-md">
                                                                                                                                                                                              Arsenal Físico y Herramientas
                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                              <p className="text-sm font-medieval text-gray-400 max-w-2xl mx-auto">
                                                                                                                                                                                                                        La magia operativa requiere vehículos tangibles. Conoce las herramientas que forjarán tu práctica.
                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                            {/* AVISO DE ENVÍOS (ADUANAS) */}
                                                                                                                                                                                                                                                  <div className="w-full max-w-4xl mx-auto mb-12 bg-black/60 border border-red-900/50 rounded-xl p-6 flex flex-col md:flex-row items-center gap-6 backdrop-blur-sm shadow-[0_0_20px_rgba(127,29,29,0.3)]">
                                                                                                                                                                                                                                                          <div className="text-4xl">⚖️</div>
                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                            <h4 className="text-red-400 font-cinzel font-bold mb-2">Aviso Importante sobre Envíos Físicos</h4>
                                                                                                                                                                                                                                                                                      <p className="text-xs md:text-sm text-gray-300 font-sans leading-relaxed text-justify">
                                                                                                                                                                                                                                                                                                  Debido a regulaciones aduanales internacionales estrictas sobre extractos de hierbas y compuestos botánicos, <strong>nuestros productos físicos (Oleums, Polvos, Velas) solo están disponibles para envío dentro de la República Mexicana</strong>. Sin embargo, nuestra biblioteca digital y servicios de magia personalizada están abiertos a nivel global sin restricción.
                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                {/* ALERTA DE LISTA DE DESEOS */}
                                                                                                                                                                                                                                                                                                                                      {wishlistMsg && (
                                                                                                                                                                                                                                                                                                                                              <div className="fixed top-24 left-1/2 transform -translate-x-1/2 bg-green-900/90 border border-green-500 text-green-100 px-6 py-3 rounded-lg shadow-[0_0_20px_rgba(34,197,94,0.4)] z-[200] font-sans text-sm animate-pulse text-center w-[90%] max-w-md">
                                                                                                                                                                                                                                                                                                                                                        {wishlistMsg}
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                            {/* GRID DE PRODUCTOS */}
                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                          {productosFuturos.map((producto) => (
                                                                                                                                                                                                                                                                                                                                                                                                    <div key={producto.id} className="bg-black/50 border border-purple-500/20 rounded-2xl overflow-hidden hover:border-purple-500/60 transition-all duration-300 group flex flex-col">
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                            {/* IMAGEN DEL PRODUCTO */}
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="relative w-full h-48 bg-white/5 flex items-center justify-center border-b border-purple-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-gray-600 font-sans text-xs uppercase tracking-widest">[Imagen Próximamente]</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Cuando tengas las imágenes, descomenta esto:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Image src={producto.image} alt={producto.name} fill className="object-cover opacity-60 group-hover:opacity-100 transition-opacity" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="absolute top-3 right-3 bg-black/80 border border-purple-500/50 text-purple-300 text-[10px] uppercase tracking-widest px-2 py-1 rounded backdrop-blur-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Próximamente
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* INFORMACIÓN */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="p-5 flex flex-col flex-grow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h4 className="text-lg font-cinzel text-gray-200 mb-3 group-hover:text-purple-300 transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {producto.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs text-gray-400 font-sans leading-relaxed text-justify mb-6 flex-grow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {producto.desc}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* BOTÓN LISTA DE DESEOS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => handleWishlist(producto.name)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full py-2.5 bg-transparent border border-gray-600 text-gray-300 hover:border-purple-400 hover:text-purple-300 rounded-lg text-xs font-bold uppercase tracking-wider transition-colors flex items-center justify-center gap-2 cursor-pointer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>🤍</span> Añadir a Deseos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }