"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function EbooksPage() {
  const router = useRouter();

    // Terreno preparado: Cada libro ya apunta a su futuro enlace independiente
      const catalogoEbooks = [
          {
                id: "verum",
                      title: "Demonios del Verum",
                            desc: "El Grimorium Verum rescatado y traducido a un método operativo para el siglo XXI. Incluye la estrategia y el ritual completo.",
                                  price: "$340 MXN",
                                        tag: "Disponible",
                                              link: "/ebooks/demonios-del-verum",
                                                    image: "/verum-portada.png"
                                                        },
                                                            {
                                                                  id: "planetaria",
                                                                        title: "Magia Planetaria",
                                                                              desc: "Guía para trabajar con las inteligencias planetarias clásicas sin dogmas antiguos. Resultados tangibles y directos.",
                                                                                    price: "Próximamente",
                                                                                          tag: "En Desarrollo",
                                                                                                link: "/ebooks/magia-planetaria",
                                                                                                      image: "/luna.png" // Puedes cambiar esto por la portada cuando la tengas
                                                                                                          }
                                                                                                            ];

                                                                                                              return (
                                                                                                                  <main className="relative min-h-screen bg-black overflow-x-hidden flex flex-col items-center pt-24 pb-16 px-4 md:px-8 text-white selection:bg-purple-900 selection:text-purple-300">
                                                                                                                        
                                                                                                                              {/* Iluminación tenue morada cayendo desde arriba */}
                                                                                                                                    <div className="fixed inset-0 pointer-events-none z-0 bg-black bg-[radial-gradient(ellipse_at_top,rgba(147,51,234,0.12),transparent_60%)]" />

                                                                                                                                          <div className="w-full max-w-5xl z-10 relative">
                                                                                                                                                  
                                                                                                                                                          {/* Botón dinámico de Regresar */}
                                                                                                                                                                  <button 
                                                                                                                                                                            onClick={() => router.back()} 
                                                                                                                                                                                      className="flex items-center gap-2 text-gray-400 hover:text-purple-400 transition-colors font-sans text-sm mb-8 md:mb-12 group cursor-pointer w-max"
                                                                                                                                                                                              >
                                                                                                                                                                                                        <span className="group-hover:-translate-x-1 transition-transform">←</span> Regresar
                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                        {/* Encabezado y Leyenda de Praxis Magick */}
                                                                                                                                                                                                                                <div className="text-center mb-16 border-b border-purple-900/30 pb-12">
                                                                                                                                                                                                                                          <h1 className="text-3xl md:text-5xl font-cinzel text-purple-300 mb-6 drop-shadow-[0_0_15px_rgba(147,51,234,0.3)]">
                                                                                                                                                                                                                                                      Tratados de Alta Magia
                                                                                                                                                                                                                                                                </h1>
                                                                                                                                                                                                                                                                          <p className="text-sm md:text-base font-medieval text-gray-300 max-w-3xl mx-auto leading-relaxed">
                                                                                                                                                                                                                                                                                      Nuestros e-books son destilaciones de alta magia moderna, creados exclusivamente bajo la autoría de Praxis Magick. 
                                                                                                                                                                                                                                                                                                  Descartamos la parafernalia innecesaria, los dogmas religiosos y el teatro para entregarte métodos 
                                                                                                                                                                                                                                                                                                              operativos, directos y adaptados al practicante del siglo XXI que busca resultados tangibles.
                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                        {/* Cuadrícula de Ebooks disponibles */}
                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12">
                                                                                                                                                                                                                                                                                                                                                          {catalogoEbooks.map((book) => (
                                                                                                                                                                                                                                                                                                                                                                      <div key={book.id} className="bg-black/40 border border-purple-500/20 rounded-2xl overflow-hidden hover:border-purple-500/50 transition-all duration-300 flex flex-col group shadow-[0_0_15px_rgba(147,51,234,0.05)] hover:shadow-[0_0_25px_rgba(147,51,234,0.15)]">
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative w-full h-64 md:h-80 bg-gray-900 flex items-center justify-center border-b border-purple-500/20 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                   <div className="absolute inset-0 bg-purple-900/10 group-hover:bg-transparent transition-colors z-10" />
                                                                                                                                                                                                                                                                                                                                                                                                                                    <Image 
                                                                                                                                                                                                                                                                                                                                                                                                                                                       src={book.image} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alt={book.title} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             fill 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="object-cover object-center group-hover:scale-105 transition-transform duration-500" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   onError={(e) => { e.currentTarget.style.display = 'none'; }} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="absolute top-4 right-4 bg-black/80 border border-purple-500/50 text-purple-300 text-[10px] uppercase tracking-widest px-2 py-1 rounded backdrop-blur-md z-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {book.tag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div className="p-6 flex flex-col flex-grow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <h2 className="text-xl md:text-2xl font-cinzel text-gray-100 mb-2">{book.title}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <span className="text-sm font-bold text-purple-400 mb-4">{book.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p className="text-xs text-gray-400 font-sans leading-relaxed mb-6 flex-grow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {book.desc}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <Link href={book.link} className="w-full py-3 bg-transparent border border-purple-500/50 text-purple-300 hover:bg-purple-900/40 text-center rounded-lg text-xs font-bold uppercase tracking-wider transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Explorar Tomo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }